services:
  - type: web
    name: ed-dashboard
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: /api
    healthCheckPath: /health
    disk:
      name: ed-dashboard-disk
      mountPath: /opt/render/project/src/public/data
      sizeGB: 1
